### ISSUE TITLE
Can't parse xml file in python2.7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [neild/py-dom-xpath#5]
```
python2.7

import xpath
from xml.dom import minidom

xml = 
minidom.parseString("<Rerservations><Rerservation><endDate>2011-03-15T11:00:00+0
8:00</endDate></Rerservation></Rerservations>")
xpath.find(xml,"/Reservations/endDate")


Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    xpath.find(xml,"/Reservations/Reservation/endDate")
  File "C:\Python27\lib\site-packages\xpath\__init__.py", line 23, in api_function
    raise e
XPathParseError: Syntax error:
<xml.dom.minidom.Document instance at 0x014A53C8>
^




```

-----
Original issue reported on code.google.com by `muden...@gmail.com` on 14 Mar 2011 at 6:45

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
opps...

expression arg shoud be first.

```

-----
Original comment by `muden...@gmail.com` on 14 Mar 2011 at 3:36

**Comment by GoogleCodeExporter** [comment]
```
does your comment mean this isn’t an issue or was it simply a typo and the 
module does indeed not work under python 2.7?

afaik this is the only python xpath implementation with painless namespace 
support (wildcards and default namespace), so i will need it.
```

-----
Original comment by `trueflyi...@gmail.com` on 7 Apr 2011 at 1:01
